### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by yukimono**
Needs further tweaking.

[Review on Reviewable](https://reviewable.io/reviews/retrospring/next/4)

### CODE REVIEW

**Comment by pixeldesu** [comment]
Does it just work with adding a `.rubocop.yml`? Rubocop itself is not configured in the project and HoundCI isn't either, so it still picks from the default configurations.

**Comment by sup** [comment]
you'd need to add a `.hound.yml` that points there

**Comment by pixeldesu** [comment]
That's what I was talking about.

**Comment by yukimono** [comment]
:V

**Comment by sup** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/retrospring/next/4)_

**Comment by sup** [comment]
(also pls format your commit messages using `nsc`)

**Comment by yukimono** [comment]
I could modify the commit messages if that'd make you happy

**Comment by yukimono** [comment]
but i'm 90% sure that breaks every intigration

**Comment by sup** [comment]
nah, its fine. we're not that far into it anyways, everyone has to get accustomed to it lol

**Comment by pixeldesu** [comment]
I started using nsc for the commits, so it's fairly easy this way.

**Pull request merged**
