### PR TITLE
Initialize Rails application

### PR DESCRIPTION
**Pull request by pixeldesu**
Pull Request to finish #1.

**Don't merge yet**, still need to get the proper database configuration working. The current one uses SQLite and we want to use PostgreSQL.

[Review on Reviewable](https://reviewable.io/reviews/retrospring/next/3)

### CODE REVIEW

**Comment by sup** [comment]
_git gud_

**Comment by talc** [comment]
Down boy.. down.

**Comment by pixeldesu** [comment]
Next goal should be to write a proper HoundCI configuration, maybe stopping the single/double quoted check to appear, because I think this would be the smallest code guideline violation we could pass through.

**Comment by sup** [comment]
@pixeldesu basically disable `Metrics/*`

**Comment by pixeldesu** [comment]
Database configuration added, this should be ready to merge!

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/retrospring/next/3#-:-K3bKjArddRlDLRlfVxT:778953193)_

**Comment by pixeldesu** [comment]
Reviewed 52 of 56 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/retrospring/next/3)_

**Pull request merged**
